### ISSUE TITLE
Add option to set custom composer dir variable

### ISSUE THREAD

**Issue by natanfelles** [stecman/composer-bash-completion-plugin#10]
https://github.com/stecman/composer-bash-completion-plugin/blob/4fda0e9bfecebaf104af0f6778a0412ea34a56fc/hooks/bash-completion#L14

On Debian, default composer dir is `$HOME/.config/composer`.

**Comment by stecman** [comment]
Can you confirm this command outputs the directory you need?

```sh
echo $XDG_DATA_HOME/composer
```

That's mentioned in the composer docs but not checked in this plugin at the moment.

**Comment by natanfelles** [comment]
Hello! 😃 

No. Terminal in/out:

```
echo $XDG_DATA_HOME/composer
/composer
```

**Comment by stecman** [comment]
Oh I see, [Composer explicitly defaults to `$HOME/.config/composer`](https://github.com/composer/composer/blob/e12e0335a4d467878093fc76e3dea592ff3e1ce3/src/Composer/Factory.php#L76) if `$XDG_CONFIG_HOME` is empty/not set.

**Comment by natanfelles** [comment]
Hi, @stecman .

Initially I had modified [this line](https://github.com/stecman/composer-bash-completion-plugin/blob/4fda0e9bfecebaf104af0f6778a0412ea34a56fc/hooks/bash-completion#L14) in your project.

But revising more, I just modified my *.bashrc* and solved:

```sh
COMPOSER_HOME="$HOME/.config/composer"
source "$COMPOSER_HOME/vendor/stecman/composer-bash-completion-plugin/hooks/bash-completion"
```

Completions are working fine now.

Thank you!

**Comment by natanfelles** [comment]
Wow that's a smarter way. I'll update here too. Thanks!

**Comment by natanfelles** [comment]
You could update the generate-hook file to:

```sh
# Generate registration code to go in a shell profile

_composercomplete_hook_dir="$(composer config home --global)/vendor/stecman/composer-bash-completion-plugin/hooks"

if [ ! -z $BASH_VERSION ]; then
	source $_composercomplete_hook_dir/bash-completion
fi

if [ ! -z $ZSH_VERSION ]; then
	source $_composercomplete_hook_dir/zsh-completion
fi

unset _composercomplete_hook_dir

```

**Comment by stecman** [comment]
I avoided doing that, since `composer config home --global` is relatively slow at around 100ms on my machine (as mentioned in the commit message above). I find slow shell start-up a pain, so I was mitigating this for others - the time all adds up, and next thing you know you have to wait several seconds to be able to use a new shell.

If someone was ok with the slow down, they could use the current generate-hook script in their shell profile like this:

```bash
source <(source $(composer config home --global)/vendor/stecman/composer-bash-completion-plugin/generate-hook)
```
