### ISSUE TITLE
Dependency of the old symfony-console-completion

### ISSUE THREAD

**Issue by przepompownia** [stecman/composer-bash-completion-plugin#12]
https://github.com/stecman/composer-bash-completion-plugin/blob/master/composer.json#L12

In result, it keeps dependency of the old `symfony/console`:
```stecman/symfony-console-completion  0.7.0    requires  symfony/console (~2.3 || ~3.0)```

**Comment by stecman** [comment]
If I understand correctly, you want the Symfony Console 4.x support from version `0.8.0` of the completion package?

I hadn't upgraded the dependencies here as I didn't believe this plugin needed the changes in newer releases, but I'm happy to if it's causing problems for you.

**Comment by przepompownia** [comment]
I have no problems but this dependency potentially prevent from upgrade other packages required by the same `composer.json`. 

I have made some manual test and encountered no problem with `0.9.0`. Three pull request are a side effect of thtse tests.

**Comment by stecman** [comment]
Awesome, thanks for all of those PRs! :+1:
