### ISSUE TITLE
Conflict with symfony/console 3.2

### ISSUE THREAD

**Issue by przepompownia** [stecman/composer-bash-completion-plugin#9]
Please try, for example,
```
composer global require stecman/composer-bash-completion-plugin dev-master
composer global require ovr/phpsa
```

**Comment by stecman** [comment]
Thanks @przepompownia :+1:

Note you'll need to update your hook from the readme for this to work with the updated version of the completion library.

**Comment by przepompownia** [comment]
The new `_composercomplete` seems to work without any probelm. 👍
